services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: dev-auth-container
    ports:
      - '4000:4000'
      - '9229:9229' # For debugger
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - dev_auth_pg_db
      - dev_auth_valkey
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development

      - PORT=${PORT}
      - DB_URL=${DB_URL}
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=${POSTGRES_PORT}
      # Redis keys
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PREFIX=${REDIS_PREFIX}

      # token keys
      - COOKIE_NAME=${COOKIE_NAME}
      - REFRESH_COOKIE_NAME=${REFRESH_COOKIE_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - TOKEN_ISSUER=${TOKEN_ISSUER}
      - TOKEN_AUDIENCE=${TOKEN_AUDIENCE}
      - JWT_REFRESH_EXPIRES_IN=${JWT_REFRESH_EXPIRES_IN}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - JWT_COOKIE_EXPIRES_IN=${JWT_COOKIE_EXPIRES_IN}

      # OAuth keys
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - APP_URL=${APP_URL}
      - HOST_NAME=${HOST_NAME}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - MAILER_SENDER=${MAILER_SENDER}
      - SOCKET_RATE_LIMIT=${SOCKET_RATE_LIMIT}

  dev_auth_pg_db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - ./.env
    # depends_on:
    ports:
      - '5432:5432'
    container_name: dev-auth-pg-db
    volumes:
      - dev_auth_pgdata:/var/lib/postgresql/data

  # dev_auth_pgadmin:
  #   image: dpage/pgadmin4:9
  #   container_name: dev-auth-pgadmin
  #   restart: unless-stopped
  #   ports:
  #     - '5050:80' # access via http://localhost:5050
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@local.com
  #     PGADMIN_DEFAULT_PASSWORD: admin123
  #   volumes:
  #     - dev_auth_pgadmin_data:/var/lib/pgadmin
  #   depends_on:
  #     - dev_auth_pg_db

  dev_auth_adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080 # access via http://localhost:8080
    container_name: dev-auth-pgadmin
    depends_on:
      - dev_auth_pg_db

  dev_auth_valkey:
    image: valkey/valkey
    container_name: dev-auth-volkey-redis-server
    env_file:
      - ./.env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    # command: "valkey-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}"
    command: >
      sh -c "valkey-server --save 60 1 --loglevel warning --requirepass \"$REDIS_PASSWORD\""
      restart: unless-stopped

    ports:
      - '6379:6379'
    volumes:
      - dev_auth_valkey_data:/data

volumes:
  dev_auth_valkey_data:
    driver: local
  dev_auth_pgdata:
  dev_auth_pgadmin_data:
