FROM node:20
# Install PostgreSQL client
RUN apt-get update && apt-get install -y postgresql-client

WORKDIR /app

COPY package*.json ./
RUN npm install --force

COPY docker-entrypoint-dev.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint-dev.sh

COPY . .
EXPOSE 4000
# ENTRYPOINT ["docker-entrypoint-dev.sh"]
ENTRYPOINT ["/usr/local/bin/docker-entrypoint-dev.sh"]
CMD ["npm", "run", "dev:local"]
